### ISSUE TITLE
bot sends the MS Time as #NUMBER

### ISSUE THREAD

**Issue by Rayjon32** [alexlyee/massdm#27]
for example when I mass!dmall text;

I see the message like;

text
#7963

and on the console is like;

Waited: 7963ms.    DMing BLABLA

how can I delete that timer

**Comment by Rayjon32** [comment]
also have a problem like this;

![image](https://user-images.githubusercontent.com/47691826/89735413-0a74bd00-da6b-11ea-81c2-14f933c96c68.png)

**Comment by Rayjon32** [comment]
just some people does like this, why would it happen ?

**Comment by alexlyee** [comment]
Likely because that user has their DMs disabled from that discord server

**Comment by alexlyee** [comment]
That timer is intentional. Don't delete it.

**Comment by Rayjon32** [comment]
Thank you very much for your answers, I tested the bot and it works great!

**Comment by alexlyee** [comment]
Glad! 😊 --Sincerely,Alex  From: Rayjon32Sent: Sunday, August 9, 2020 12:30 PMTo: alexlyee/massdmCc: Alex Lindstrom; State changeSubject: Re: [alexlyee/massdm] bot sends the MS Time as #NUMBER (#27) Thank you very much for your answers, I tested the bot and it works great!—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
