### ISSUE TITLE
[SUGGESTION] Whats the point in perms?

### ISSUE THREAD

**Issue by Motzumoto** [alexlyee/massdm#6]
whats the point in having the perms thing, i wanna mass dm a server i hate with my user account, but it says i need admin, why?

**Comment by alexlyee** [comment]
A server you hate, or have? Because DMing EVERYONE is a much stronger power than simply doing @everyone. And thus, shouldn't need to be done as often, so when it does have to, a server owner can do it themselves. If you truly own the server, and you cannot DM them because it states it doesn't have proper permissions, than you either don't actually own the server or haven't properly set up the bot.

**Comment by alexlyee** [comment]
owner could add people to have the ability to use the command
